// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLeafAlloc = "leaf_alloc"

// LeafAlloc mapped from table <leaf_alloc>
type LeafAlloc struct {
	BizTag      string    `gorm:"column:biz_tag;primaryKey" json:"biz_tag"`
	MaxID       int64     `gorm:"column:max_id;not null;default:1" json:"max_id"`
	Step        int64     `gorm:"column:step;not null" json:"step"`
	Description string    `gorm:"column:description" json:"description"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName LeafAlloc's table name
func (*LeafAlloc) TableName() string {
	return TableNameLeafAlloc
}
